FROM openjdk:8

WORKDIR /app

COPY data-api/src /app/src
COPY data-api/gradle /app/gradle
COPY data-api/build.gradle /app/build.gradle
COPY data-api/settings.gradle /app/settings.gradle
COPY data-api/gradlew /app/gradlew
COPY wait-for-it.sh /app/wait-for-it.sh

RUN chmod +x wait-for-it.sh \
    && ./gradlew clean build -x test
