FROM node:12.18.4

WORKDIR /app

ENV PATH /app/node_modules/.bin:$PATH

COPY frontend/src /app/src
COPY frontend/public /app/public
COPY frontend/package.json /app/package.json
COPY frontend/package-lock.json /app/package-lock.json

RUN npm install
RUN npm install react-scripts@3.4.1 -g