version: "2"

services:

  data-api:
    build:
      context: .
      dockerfile: $PWD/Dockerfile_data-api
    ports:
      - "8081:8080"
    command: ["/app/wait-for-it.sh", "db:3306", "--", "java", "-jar", "/app/build/libs/data-api-1.0.jar"]

  payment-api:
    build:
      context: .
      dockerfile: $PWD/Dockerfile_payment-api
    ports:
      - "8082:8080"
    command: ["java", "-jar", "/app/build/libs/payment-api-1.0.jar"]

  frontend:
    build:
      context: .
      dockerfile: $PWD/Dockerfile_frontend
    stdin_open: true
    ports:
      - "3000:3000"
    command: ["npm", "start"]

  db:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=pass
    volumes:
      - $PWD/db.sql:/docker-entrypoint-initdb.d/init.sql
